feat: Add zkUsePaymaster cheatcode docs
matter-labs/foundry-zksync-book pull request #24
Opened 2024-09-26 13:08 UTC by Jrigada

# Updates to zkUsePaymaster cheatcode documentation

This PR enhances the documentation for the `zkUsePaymaster` cheatcode in the ZkSync-specific cheatcodes section.

1. Added a detailed example of a custom paymaster contract implementation.
2. Included steps for deploying the paymaster contract, both in a test/script and using the `forge create` command.
3. Provided an example of how to use the `zkUsePaymaster` cheatcode with the custom paymaster.
4. Added references to additional resources

2024-09-27 15:02 UTC, dutterbutter commented
@Jrigada does this cheatcode also work for approval flow paymasters?

2024-10-04 14:11 UTC, Karrq requested changes

2024-10-04 14:11 UTC, Karrq commented on src/zksync-specifics/cheatcodes/zk-use-paymaster.md
> +For more examples, see the [Foundry ZkSync Paymaster Tests](TBD).
Don't we have a test here that we can link?

2024-10-04 14:16 UTC, Jrigada commented
Hey @dutterbutter yes, it's generic. It depends on which parameters you encode and pass it with the cheatcode.

2024-10-04 14:16 UTC, merged