docs: ZkUseFactoryDep cheatcode documentation
matter-labs/foundry-zksync-book pull request #45
Opened 2024-10-30 15:09 UTC by Jrigada

2024-10-30 19:40 UTC, nbaztec approved these changes

2024-10-31 10:34 UTC, Karrq requested changes

2024-10-31 10:34 UTC, Karrq commented on src/zksync-specifics/cheatcodes/zk-use-factory-dep.md
> +Enables marking a bytecode as a factory dependency for the next CREATE or CALL and cleared after.
```suggestion
Marks a given contract as a factory dependency only for the next CREATE or CALL, unmarking it afterwards, similar to [`prank`](../../cheatcodes/prank.md).
```

2024-10-31 10:34 UTC, Karrq commented on src/zksync-specifics/cheatcodes/zk-use-factory-dep.md
> +This cheatcode is useful when deploying contracts through factories, as it allows marking bytecode as a factory dependency and deploying contracts by passing their bytecode hash to the factory.
```suggestion
This cheatcode is useful when deploying contracts through factories that do not depend directly on a given contract, as it allows to explicitly mark this type of contract as a factory dependency, allowing the factory to deploy the contract.

More information on factory dependencies in the [official ZKsync docs](https://docs.zksync.io/build/developer-reference/ethereum-differences/contract-deployment#note-on-factory_deps).
```

2024-10-31 10:34 UTC, Karrq commented on src/zksync-specifics/examples/smart-account.md
> +zkforge script ./script/DeployMultisig.s.sol:DeployMultisig --rpc-url <RPC_URL> --private-key <PRIVATE_KEY> --broadcast --via-ir --system-mode true --zksync
are we officially going for `zkforge`?

2024-10-31 10:34 UTC, Karrq commented on src/zksync-specifics/examples/smart-account.md
> +zkforge script ./script/DeployMultisig.s.sol:DeployMultisig --rpc-url <RPC_URL> --private-key <PRIVATE_KEY> --broadcast --via-ir --system-mode true --zksync
```suggestion
zkforge script ./script/DeployMultisig.s.sol:DeployMultisig --rpc-url <RPC_URL> --private-key <PRIVATE_KEY> --broadcast --via-ir --zk-enable-eravm-extensions --zksync
```

2024-10-31 10:34 UTC, Karrq commented on src/zksync-specifics/cheatcodes/zk-use-factory-dep.md
> +    Factory factory = new Factory(multisigBytecodeHash);
Can we have a few extra lines to explain what's happening here? Specifically: 
* `Factory` does not depend on `TwoUserMultisig` directly
* We thus need to mark it explicitly

2024-10-31 10:34 UTC, Karrq commented on src/zksync-specifics/examples/smart-account.md
> +        console.log("Multisig deployed at: ", multisigAddress);
I don't understand this section - we just deployed `AAFactory` and even used it, but now we do the same? But with a different constructor even?
Above we have `bytecodeHash` and here it's `owner1,owner2` encoded...
Also technically speaking we can already make use of the `Create2Factory` implicitly with the CREATE2 syntax ;)

2024-10-31 10:34 UTC, Karrq commented on src/zksync-specifics/cheatcodes/zk-use-factory-dep.md
> +This cheatcode is useful when deploying contracts through factories, as it allows marking bytecode as a factory dependency and deploying contracts by passing their bytecode hash to the factory.
I like concise but for documentation we should be explicit on what problem this addresses, how it helps, and what you can do with it, outside of the examples later

2024-10-31 12:10 UTC, Jrigada commented on src/zksync-specifics/examples/smart-account.md
> +zkforge script ./script/DeployMultisig.s.sol:DeployMultisig --rpc-url <RPC_URL> --private-key <PRIVATE_KEY> --broadcast --via-ir --system-mode true --zksync
Good catch

2024-10-31 15:45 UTC, tomimor reviewed
💯

2024-10-31 16:05 UTC, Karrq approved these changes

2024-10-31 16:06 UTC, merged